In [2]:
import pandas as pd

df = pd.read_csv("global_disaster_response_2018_2024.csv")

print(df.info())
print(df.isnull().sum())

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   date                       50000 non-null  str
 1   country                    50000 non-null  str
 2   disaster_type              50000 non-null  str
 3   severity_index             50000 non-null  float64
 4   casualties                 50000 non-null  int64
 5   economic_loss_usd          50000 non-null  float64
 6   response_time_hours        50000 non-null  float64
 7   aid_amount_usd             50000 non-null  float64
 8   response_efficiency_score  50000 non-null  float64
 9   recovery_days              50000 non-null  int64
 10  latitude                   50000 non-null  float64
 11  longitude                  50000 non-null  float64
dtypes: float64(7), int64(2), str(3)
memory usage: 4.6 MB
None
date                         0
country                      0
disaster_type                0
severity_index               0
casualties                   0
economic_loss_usd            0
response_time_hours          0
aid_amount_usd               0
response_efficiency_score    0
recovery_days                0
latitude                     0
longitude                    0
dtype: int64

In [4]:
#  normaliser les colonnes 
df.columns = (df.columns.str.strip().str.lower().str.replace("","_").str.replace("","_"))
df.columns

Index(['_______________d_______________a_______________t_______________e_______________',
       '_______________c_______________o_______________u_______________n_______________t_______________r_______________y_______________',
       '_______________d_______________i_______________s_______________a_______________s_______________t_______________e_______________r_______________________________t_______________y_______________p_______________e_______________',
       '_______________s_______________e_______________v_______________e_______________r_______________i_______________t_______________y_______________________________i_______________n_______________d_______________e_______________x_______________',
       '_______________c_______________a_______________s_______________u_______________a_______________l_______________t_______________i_______________e_______________s_______________',
       '_______________e_______________c_______________o_______________n_______________o_______________m_______________i_______________c_______________________________l_______________o_______________s_______________s_______________________________u_______________s_______________d_______________',
       '_______________r_______________e_______________s_______________p_______________o_______________n_______________s_______________e_______________________________t_______________i_______________m_______________e_______________________________h_______________o_______________u_______________r_______________s_______________',
       '_______________a_______________i_______________d_______________________________a_______________m_______________o_______________u_______________n_______________t_______________________________u_______________s_______________d_______________',
       '_______________r_______________e_______________s_______________p_______________o_______________n_______________s_______________e_______________________________e_______________f_______________f_______________i_______________c_______________i_______________e_______________n_______________c_______________y_______________________________s_______________c_______________o_______________r_______________e_______________',
       '_______________r_______________e_______________c_______________o_______________v_______________e_______________r_______________y_______________________________d_______________a_______________y_______________s_______________',
       '_______________l_______________a_______________t_______________i_______________t_______________u_______________d_______________e_______________',
       '_______________l_______________o_______________n_______________g_______________i_______________t_______________u_______________d_______________e_______________'],
      dtype='str')

In [6]:
df = pd.read_csv("global_disaster_response_2018_2024.csv", sep=",", encoding="utf-8")
print(df.columns)

Index(['date', 'country', 'disaster_type', 'severity_index', 'casualties',
       'economic_loss_usd', 'response_time_hours', 'aid_amount_usd',
       'response_efficiency_score', 'recovery_days', 'latitude', 'longitude'],
      dtype='str')

In [7]:
#convertir les types:
df["date"] = pd.to_datetime(df["date"], errors="coerce")

In [11]:
# detecter des valeurs aberrante:
import numpy as np
q01 = df["economic_loss_usd"].quantile(0.01)
q99 = df["economic_loss_usd"].quantile(0.99)
df["economic_loss_usd"] =df["economic_loss_usd"].clip(q01, q99)

q01 =df["response_time_hours"].quantile(0.01)
q99 = df["response_time_hours"].quantile(0.99)
df["response_time_hours"] = df["response_time_hours"].clip(q01, q99)

df.describe()

,date,severity_index,casualties,economic_loss_usd,response_time_hours,aid_amount_usd,response_efficiency_score,recovery_days,latitude,longitude
count,50000,50000.000000,50000.000000,5.000000e+04,50000.000000,5.000000e+04,50000.000000,50000.000000,50000.000000,50000.000000
mean,2021-07-02 13:05:39.840000,5.015769,100.591140,5.050053e+06,12.149863,2.500003e+05,87.574025,49.682560,0.231205,0.089889
min,2018-01-01 00:00:00,1.000000,0.000000,1.846402e+05,1.000000,1.660000e+01,29.750000,2.000000,-59.994000,-169.998000
25%,2019-10-07 00:00:00,3.660000,51.000000,2.585513e+06,6.270000,1.429663e+05,83.060000,36.000000,-29.848250,-85.551750
50%,2021-06-27 00:00:00,4.990000,91.000000,4.548351e+06,10.510000,2.305365e+05,89.180000,49.000000,0.267500,0.390500
75%,2023-04-02 00:00:00,6.340000,138.000000,6.950615e+06,15.450000,3.352259e+05,94.700000,63.000000,30.488250,85.665000
max,2024-12-31 00:00:00,10.000000,524.000000,1.468041e+07,49.320003,1.126465e+06,100.000000,112.000000,59.997000,169.999000
std,NaN,1.942843,65.052064,3.198235e+06,9.115178,1.432275e+05,10.188961,20.098944,34.759662,98.380208

In [ ]:
#creation fichier nettoyé

df.to_csv("catastrophe_donnees_nettoyer.csv" , index=False)

In [13]:
#apercu du data set 

df.head()
df.tail()
df.sample(10)

,date,country,disaster_type,severity_index,casualties,economic_loss_usd,response_time_hours,aid_amount_usd,response_efficiency_score,recovery_days,latitude,longitude
17491,2023-03-01,France,Flood,5.18,76,8422001.97,3.62,250620.34,96.06,49,36.891,-8.473
39195,2024-01-10,Greece,Tornado,4.03,111,3265548.96,4.56,393380.71,90.16,42,12.600,72.987
31624,2020-05-10,Brazil,Storm Surge,5.36,121,4142930.22,11.92,425901.32,90.47,54,-4.966,-45.952
30531,2021-08-23,Greece,Drought,3.94,30,6831994.40,11.36,119141.09,84.85,37,14.107,-100.572
29319,2022-04-14,Germany,Tornado,2.28,24,842961.34,15.88,83278.67,82.31,21,-6.135,-53.448
7291,2019-07-04,Bangladesh,Volcanic Eruption,3.90,63,4639265.16,15.17,220586.83,80.35,35,-50.995,-17.401
19642,2019-02-22,Nigeria,Landslide,5.35,63,10412906.90,8.10,348072.95,93.73,48,31.300,-71.173
8125,2024-09-23,Indonesia,Wildfire,6.07,18,9323123.42,7.50,364135.91,100.00,62,36.695,114.472
46488,2019-05-16,India,Drought,4.93,128,1766550.86,9.32,356199.06,88.63,48,9.665,-121.554
10804,2023-05-12,Spain,Extreme Heat,7.60,173,10701990.72,8.28,251482.01,92.96,74,45.030,-126.284

In [14]:
#stat descriptives globales


df.describe(include="all")

,date,country,disaster_type,severity_index,casualties,economic_loss_usd,response_time_hours,aid_amount_usd,response_efficiency_score,recovery_days,latitude,longitude
count,50000,50000,50000,50000.000000,50000.000000,5.000000e+04,50000.000000,5.000000e+04,50000.000000,50000.000000,50000.000000,50000.000000
unique,NaN,20,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,Brazil,Landslide,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,2591,5130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,2021-07-02 13:05:39.840000,NaN,NaN,5.015769,100.591140,5.050053e+06,12.149863,2.500003e+05,87.574025,49.682560,0.231205,0.089889
min,2018-01-01 00:00:00,NaN,NaN,1.000000,0.000000,1.846402e+05,1.000000,1.660000e+01,29.750000,2.000000,-59.994000,-169.998000
25%,2019-10-07 00:00:00,NaN,NaN,3.660000,51.000000,2.585513e+06,6.270000,1.429663e+05,83.060000,36.000000,-29.848250,-85.551750
50%,2021-06-27 00:00:00,NaN,NaN,4.990000,91.000000,4.548351e+06,10.510000,2.305365e+05,89.180000,49.000000,0.267500,0.390500
75%,2023-04-02 00:00:00,NaN,NaN,6.340000,138.000000,6.950615e+06,15.450000,3.352259e+05,94.700000,63.000000,30.488250,85.665000
max,2024-12-31 00:00:00,NaN,NaN,10.000000,524.000000,1.468041e+07,49.320003,1.126465e+06,100.000000,112.000000,59.997000,169.999000
std,NaN,NaN,NaN,1.942843,65.052064,3.198235e+06,9.115178,1.432275e+05,10.188961,20.098944,34.759662,98.380208

In [15]:
# distribution des catatstrophes par pays

df['country'].value_counts().head(20)

country
Brazil           2591
Australia        2563
Turkey           2554
Bangladesh       2553
Spain            2543
China            2539
Chile            2529
Nigeria          2528
Germany          2526
India            2509
Greece           2503
Italy            2503
South Africa     2497
Japan            2472
Indonesia        2467
Canada           2438
Philippines      2437
Mexico           2433
United States    2413
France           2402
Name: count, dtype: int64

In [ ]:
# typologie des catastrophes les plus frequentes : 
df['disaster_type ]

In [22]:
types_uniques = df["disaster_type"].unique()
types_uniques

mapping = mapping = {
    "Earthquake": "Tremblement de terre",
    "Flood": "Inondation",
    "Wildfire": "Feu de forêt",
    "Hurricane": "Ouragan",
    "Tornado": "Tornade",
    "Drought": "Sécheresse",
    "Volcanic Eruption": "Éruption volcanique",
    "Tsunami": "Tsunami",
    "Landslide": "Glissement de terrain",
    "Cyclone": "Cyclone",
    "Blizzard": "Blizzard",
    "Heatwave": "Canicule"
}

df["disaster_type_fr"] = df["disaster_type"].map(mapping)

In [23]:
mapping_colonnes = {
    "Date": "Date",
    "Country": "Pays",
    "Disaster_type": "Type_catastrophe_en",
    "Severity_index": "Indice_severite",
    "Casualties": "Victimes",
    "Economic_loss_usd": "Pertes_economiques_usd",
    "Response_time_hours": "Temps_reponse_heures",
    "Aid_amount_usd": "Aide_financiere_usd",
    "Response_efficiency_score": "Score_efficacite_reponse",
    "Recovery_days": "Jours_retablissement",
    "Latitude": "Latitude",
    "Longitude": "Longitude"
}

df = df.rename(columns=mapping_colonnes)

In [24]:
df.to_csv("disasters_clean_fr.csv", index=False)
print("CSV nettoyé et traduit généré : disasters_clean_fr.csv")

CSV nettoyé et traduit généré : disasters_clean_fr.csv